/* eslint-disable no-unused-vars */
let countNum = 10;
const BLUE_HEX = 0x0000ff;
const UNMASK = 0o0022;
const THREE_BIN = 0b11;
const ROOM_TEMP = 21.5;
const BIG_NUMBER = 3.0e15;
const SMALL_NUMBER = -1.6e-19;
const INFINITY = Infinity;
const NEGATIVE_INFINITY = -Infinity;
const NOT_A_NUMBER = NaN;
